all_targets/dark_north.fits : 
	python prepare_DR8_targets.py
    
all_targets/dark_south.fits : 
	python prepare_DR8_targets.py

all_targets/bright_north.fits : 
	python prepare_DR8_targets.py
    
all_targets/bright_south.fits : 
	python prepare_DR8_targets.py
