#!/bin/bash
#SBATCH -N 1
#SBATCH -C amd
#SBATCH -t 48:00:00
#SBATCH -q bigmem

export OMP_NUM_THREADS=32

srun -n 1 fba_run --targets inputs/mtl_updated_lya_0.20_full_sky_dark_sv3.fits  --sky inputs/sky.fits --footprint inputs/dark_tiles.fits --rundate 2021-03-17T23:20:01 --dir fba_mtl_dark_full_sky/ --overwrite --no_redistribute 

srun -n 1 fba_run --targets inputs/mtl_full_sky_bright_sv3.fits  --sky inputs/sky.fits --footprint inputs/bright_tiles.fits --rundate 2021-03-17T23:20:01 --dir fba_mtl_bright_full_sky/ --overwrite --no_redistribute 




